import test from "node:test";
import assert from "node:assert/strict";
import { EdgeOneBlobWorkLogRepository } from "../src/work-log/repositories.js";
import { EdgeOneWeeklyReportRepository } from "../src/work-log/weekly-report-repositories.js";

class CasBlob{constructor(){this.data=new Map();this.sequence=0}async getWithHeaders(key){const x=this.data.get(key);return x?{data:x.bytes,etag:x.etag}:null}async putIfAbsent(key,bytes){if(this.data.has(key))return false;this.data.set(key,{bytes,etag:String(++this.sequence)});return true}async compareAndSet(key,etag,bytes){const x=this.data.get(key);if((x?.etag||null)!==(etag||null))return false;this.data.set(key,{bytes,etag:String(++this.sequence)});return true}}

test("EDGEONE-MANUAL create update delete and weekly inclusion converge",async()=>{let now=100;const repo=new EdgeOneBlobWorkLogRepository(new CasBlob(),{now:()=>++now,random:(()=>{let n=0;return()=>String(++n).padStart(24,"0")})()}),subject="self",log=await repo.createWorkLog(subject,{localDate:"2026-08-29",title:"工作记录"});await repo.createItem(subject,log.logId,{itemId:"manual",title:"整理设备维修记录",content:"整理设备维修记录"},log.version);let current=await repo.getWorkLog(subject,log.logId);assert.equal(current.summary,"1、整理设备维修记录。");const weekly=new EdgeOneWeeklyReportRepository(repo,{now:()=>++now}),created=await weekly.generate(subject,"2026-08-24","2026-08-30");assert.match(created.report.content,/整理设备维修记录。/);const digest=created.report.sourceDigest;await repo.updateItem(subject,log.logId,"manual",{title:"整理设备台账",content:"整理设备台账"},current.version);current=await repo.getWorkLog(subject,log.logId);assert.equal(current.summary,"1、整理设备台账。");const rebuilt=await weekly.generate(subject,"2026-08-24","2026-08-30");assert.notEqual(rebuilt.report.sourceDigest,digest);assert.match(rebuilt.report.content,/整理设备台账。/);await repo.deleteItem(subject,log.logId,"manual",current.version);current=await repo.getWorkLog(subject,log.logId);assert.equal(current.summary,"");await assert.rejects(()=>weekly.generate(subject,"2026-08-24","2026-08-30"),/NO_SOURCE_DATA/)});

test("EDGEONE-MANUAL idempotent replay and user summary protection",async()=>{const repo=new EdgeOneBlobWorkLogRepository(new CasBlob(),{random:()=>"x".repeat(24)}),log=await repo.createWorkLog("self",{localDate:"2026-08-29",title:"工作记录",summary:"用户摘要"});let current=await repo.mutateAggregate("self",log.logId,value=>({...value,userEditedSummary:true}));await repo.createItem("self",log.logId,{itemId:"manual",title:"人工事项",content:"人工事项"},current.version);current=await repo.getWorkLog("self",log.logId);const version=current.version;await repo.createItem("self",log.logId,{itemId:"manual",title:"人工事项",content:"人工事项"},current.version);const after=await repo.getWorkLog("self",log.logId);assert.equal(after.items.length,1);assert.equal(after.version,version);assert.equal(after.summary,"用户摘要")});
