import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {unstable_dev} from "wrangler";
import { buildExportModel, ExportService, exportWorkbookRows, MemoryArtifactStore, MemoryExportRepository, renderExportJson, renderExportXlsx } from "../src/work-log/export-core.generated.js";
import { EdgeOneArtifactStore, EdgeOneExportStore } from "../src/work-log/export-storage.js";
const log={logId:"l",localDate:"2026-08-27",status:"FINAL",version:1,createdAt:1,title:"日志"},capture={captureId:"c",clientCaptureId:"cc",jiluCode:"JL-260827-0123456789AB-X",capturedAt:"2026-08-27T00:00:00.000Z",localDate:"2026-08-27",fields:[{fieldId:"f",labelSnapshot:"值",type:"text",value:"=1+1",visibleInPhoto:true,source:"USER"}],photoSha256:"a".repeat(64)};
const source={async listWorkLogs(s,{offset}){return offset?[]:[log]},async getWorkLog(){return{...log,items:[{itemId:"i",title:"事项"}],captureAssociations:[{itemId:"i",captureId:"c"}]}},async getCaptureById(){return capture}};
class Blob {constructor(){this.data=new Map()}async getWithHeaders(k){const v=this.data.get(k);return v?{data:v}:null}async set(k,v){this.data.set(k,v)}async delete(k){this.data.delete(k)}}
const query={dateFrom:"2026-08-01",dateTo:"2026-08-31",includeCaptures:true};
test("SQLite D1 EdgeOne share byte-identical export core",()=>{const server=fs.readFileSync(new URL("../../shuiyin-server/src/work-log/export-core.js",import.meta.url),"utf8"),edge=fs.readFileSync(new URL("../src/work-log/export-core.generated.js",import.meta.url),"utf8");assert.equal(edge,server)});
test("EXPORT_PROVIDER_PARITY model JSON XLSX semantics",async()=>{const models=await Promise.all([1,2,3].map(()=>buildExportModel({repository:source,subjectId:"s",query,now:()=>100})));assert.deepEqual(models[0],models[1]);assert.deepEqual(exportWorkbookRows(models[0]),exportWorkbookRows(models[2]));assert.deepEqual(renderExportJson(models[0]),renderExportJson(models[2]));assert.equal(renderExportXlsx(models[0]).length,renderExportXlsx(models[2]).length)});
test("EdgeOne subject index jobs private artifacts and expiry",async()=>{const blob=new Blob(),store=new EdgeOneExportStore(blob),service=new ExportService({repository:source,jobs:store,artifacts:new EdgeOneArtifactStore(store),now:()=>100,id:()=>"exp_edge"});const job=await service.create("A",{format:"XLSX",clientExportId:"client",query});assert.equal(job.status,"READY");assert.equal((await service.list("A")).length,1);assert.equal((await service.list("B")).length,0);assert.ok((await service.download("A","exp_edge")).bytes.length>1000);await assert.rejects(()=>service.download("B","exp_edge"),/EXPORT_NOT_FOUND/);assert.ok([...blob.data.keys()].every(k=>k.startsWith("wl:v1:export:")))});
test("D1 migration job metadata and authenticated export HTTP",async(t)=>{const worker=await unstable_dev("tests/fixtures/d1-work-log-export-worker.js",{config:"wrangler.jsonc",local:true,persist:false,logLevel:"none"});t.after(()=>worker.stop());const call=(path,{method="GET",body}={})=>worker.fetch(`http://local${path}`,{method,headers:{authorization:"Bearer creator",...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});let response=await call("/v1/work-logs",{method:"POST",body:{localDate:"2026-08-27",timezone:"Asia/Shanghai",title:"D1 Export",summary:"",projectId:null,projectNameSnapshot:null}});assert.equal(response.status,201);response=await call("/v1/exports",{method:"POST",body:{format:"JSON",clientExportId:`d1_${Date.now()}`,query:{dateFrom:"2026-08-01",dateTo:"2026-08-31",includeCaptures:false}}});assert.equal(response.status,202);const job=(await response.json()).export;assert.equal(job.status,"READY");response=await call(`/v1/exports/${job.exportId}/download`);assert.equal(response.status,200);assert.match(response.headers.get("content-type"),/application\/json/);const model=await response.json();assert.equal(model.schemaVersion,2);assert.ok(model.workLogs.some(x=>x.title==="D1 Export"));assert.doesNotMatch(JSON.stringify(model),/captureId|photoSha256|jiluCode/)});
